### ISSUE TITLE
Warn on unused IO/Task

### ISSUE THREAD

**Issue by samhh** [buildo/eslint-plugin-fp-ts#54]
Is it possible to warn on unused `IO` or `Task`? I've seen cases where refactoring e.g. `(x: string) => void` to `(x: string) => IO<void>` can cause business logic to break with no warning from the compiler, e.g. in a Redux side effect where you need to unwrap and exit the monadic context.

**Comment by gabro** [comment]
Hi @samhh, I actually need something like that as well. I took a first stab in #55, although I think it won't directly cover your use case (returning `IO` where `void` is expected).

That PR at least lays down the infrastructure and catches similar mistakes, I will try to follow up and see whether we can cover your original use case

**Comment by gabro** [comment]
This has been released in v0.2.1 by the way 😄
